syntax = "proto3";

package monitoring;

message GraspCandidate {
    message Pose {
        float x = 1;
        float y = 2;
        float z = 3;
        float qx = 4;
        float qy = 5;
        float qz = 6;
        float qw = 7;
    }

    string id = 1;
    uint64 timestamp = 2;
    bool success = 3;
    Pose pose = 4;
    float score = 5;
}

message RobotConfig {
    float q0 = 1;
    float q1 = 2;
    float q2 = 3;
    float q3 = 4;
    float q4 = 5;
    float q5 = 6;
}

message PickPlan {
    string id = 1;
    uint64 timestamp = 2;
    bool success = 3;
    double start_time = 4;
    double end_time = 5;
    repeated RobotConfig control_points = 6;
}

message PickStatus {
    enum Status {
        SUCCESS = 0;
        FAILURE = 1;
        IN_PROGRESS = 2;
    }

    string id = 1;
    uint64 timestamp = 2;
    Status status = 3;
    RobotConfig q = 4;
}

message Envelope {
    oneof payload {
        GraspCandidate graspCandidate = 1;
        PickPlan pickPlan = 2;
        PickStatus pickStatus = 3;
    }
}
