"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class GraspCandidate(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Pose(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        X_FIELD_NUMBER: _builtins.int
        Y_FIELD_NUMBER: _builtins.int
        Z_FIELD_NUMBER: _builtins.int
        QX_FIELD_NUMBER: _builtins.int
        QY_FIELD_NUMBER: _builtins.int
        QZ_FIELD_NUMBER: _builtins.int
        QW_FIELD_NUMBER: _builtins.int
        x: _builtins.float
        y: _builtins.float
        z: _builtins.float
        qx: _builtins.float
        qy: _builtins.float
        qz: _builtins.float
        qw: _builtins.float
        def __init__(
            self,
            *,
            x: _builtins.float = ...,
            y: _builtins.float = ...,
            z: _builtins.float = ...,
            qx: _builtins.float = ...,
            qy: _builtins.float = ...,
            qz: _builtins.float = ...,
            qw: _builtins.float = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["qw", b"qw", "qx", b"qx", "qy", b"qy", "qz", b"qz", "x", b"x", "y", b"y", "z", b"z"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    ID_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    POSE_FIELD_NUMBER: _builtins.int
    SCORE_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    timestamp: _builtins.int
    success: _builtins.bool
    score: _builtins.float
    @_builtins.property
    def pose(self) -> Global___GraspCandidate.Pose: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        timestamp: _builtins.int = ...,
        success: _builtins.bool = ...,
        pose: Global___GraspCandidate.Pose | None = ...,
        score: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pose", b"pose"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "pose", b"pose", "score", b"score", "success", b"success", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GraspCandidate: _TypeAlias = GraspCandidate  # noqa: Y015

@_typing.final
class RobotConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    Q0_FIELD_NUMBER: _builtins.int
    Q1_FIELD_NUMBER: _builtins.int
    Q2_FIELD_NUMBER: _builtins.int
    Q3_FIELD_NUMBER: _builtins.int
    Q4_FIELD_NUMBER: _builtins.int
    Q5_FIELD_NUMBER: _builtins.int
    q0: _builtins.float
    q1: _builtins.float
    q2: _builtins.float
    q3: _builtins.float
    q4: _builtins.float
    q5: _builtins.float
    def __init__(
        self,
        *,
        q0: _builtins.float = ...,
        q1: _builtins.float = ...,
        q2: _builtins.float = ...,
        q3: _builtins.float = ...,
        q4: _builtins.float = ...,
        q5: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["q0", b"q0", "q1", b"q1", "q2", b"q2", "q3", b"q3", "q4", b"q4", "q5", b"q5"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RobotConfig: _TypeAlias = RobotConfig  # noqa: Y015

@_typing.final
class PickPlan(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    START_TIME_FIELD_NUMBER: _builtins.int
    END_TIME_FIELD_NUMBER: _builtins.int
    CONTROL_POINTS_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    timestamp: _builtins.int
    success: _builtins.bool
    start_time: _builtins.float
    end_time: _builtins.float
    @_builtins.property
    def control_points(self) -> _containers.RepeatedCompositeFieldContainer[Global___RobotConfig]: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        timestamp: _builtins.int = ...,
        success: _builtins.bool = ...,
        start_time: _builtins.float = ...,
        end_time: _builtins.float = ...,
        control_points: _abc.Iterable[Global___RobotConfig] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["control_points", b"control_points", "end_time", b"end_time", "id", b"id", "start_time", b"start_time", "success", b"success", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PickPlan: _TypeAlias = PickPlan  # noqa: Y015

@_typing.final
class PickStatus(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Status:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[PickStatus._Status.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        SUCCESS: PickStatus._Status.ValueType  # 0
        FAILURE: PickStatus._Status.ValueType  # 1
        IN_PROGRESS: PickStatus._Status.ValueType  # 2

    class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...
    SUCCESS: PickStatus.Status.ValueType  # 0
    FAILURE: PickStatus.Status.ValueType  # 1
    IN_PROGRESS: PickStatus.Status.ValueType  # 2

    ID_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    Q_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    timestamp: _builtins.int
    status: Global___PickStatus.Status.ValueType
    @_builtins.property
    def q(self) -> Global___RobotConfig: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        timestamp: _builtins.int = ...,
        status: Global___PickStatus.Status.ValueType = ...,
        q: Global___RobotConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["q", b"q"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "q", b"q", "status", b"status", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PickStatus: _TypeAlias = PickStatus  # noqa: Y015

@_typing.final
class Envelope(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    GRASPCANDIDATE_FIELD_NUMBER: _builtins.int
    PICKPLAN_FIELD_NUMBER: _builtins.int
    PICKSTATUS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def graspCandidate(self) -> Global___GraspCandidate: ...
    @_builtins.property
    def pickPlan(self) -> Global___PickPlan: ...
    @_builtins.property
    def pickStatus(self) -> Global___PickStatus: ...
    def __init__(
        self,
        *,
        graspCandidate: Global___GraspCandidate | None = ...,
        pickPlan: Global___PickPlan | None = ...,
        pickStatus: Global___PickStatus | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["graspCandidate", b"graspCandidate", "payload", b"payload", "pickPlan", b"pickPlan", "pickStatus", b"pickStatus"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["graspCandidate", b"graspCandidate", "payload", b"payload", "pickPlan", b"pickPlan", "pickStatus", b"pickStatus"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["graspCandidate", "pickPlan", "pickStatus"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___Envelope: _TypeAlias = Envelope  # noqa: Y015
