# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry/telemetry.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'telemetry/telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19telemetry/telemetry.proto\x12\x1aso101_monitoring.telemetry\"\xe7\x01\n\x0eGraspCandidate\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12=\n\x04pose\x18\x04 \x01(\x0b\x32/.so101_monitoring.telemetry.GraspCandidate.Pose\x12\r\n\x05score\x18\x05 \x01(\x02\x1aW\n\x04Pose\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\n\n\x02qx\x18\x04 \x01(\x02\x12\n\n\x02qy\x18\x05 \x01(\x02\x12\n\n\x02qz\x18\x06 \x01(\x02\x12\n\n\x02qw\x18\x07 \x01(\x02\"U\n\x0bRobotConfig\x12\n\n\x02q0\x18\x01 \x01(\x02\x12\n\n\x02q1\x18\x02 \x01(\x02\x12\n\n\x02q2\x18\x03 \x01(\x02\x12\n\n\x02q3\x18\x04 \x01(\x02\x12\n\n\x02q4\x18\x05 \x01(\x02\x12\n\n\x02q5\x18\x06 \x01(\x02\"\xa1\x01\n\x08PickPlan\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x12\n\nstart_time\x18\x04 \x01(\x01\x12\x10\n\x08\x65nd_time\x18\x05 \x01(\x01\x12?\n\x0e\x63ontrol_points\x18\x06 \x03(\x0b\x32\'.so101_monitoring.telemetry.RobotConfig\"\xd3\x01\n\nPickStatus\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12=\n\x06status\x18\x03 \x01(\x0e\x32-.so101_monitoring.telemetry.PickStatus.Status\x12\x32\n\x01q\x18\x04 \x01(\x0b\x32\'.so101_monitoring.telemetry.RobotConfig\"3\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x12\x0f\n\x0bIN_PROGRESS\x10\x02\"\xd3\x01\n\x08\x45nvelope\x12\x44\n\x0egraspCandidate\x18\x01 \x01(\x0b\x32*.so101_monitoring.telemetry.GraspCandidateH\x00\x12\x38\n\x08pickPlan\x18\x02 \x01(\x0b\x32$.so101_monitoring.telemetry.PickPlanH\x00\x12<\n\npickStatus\x18\x03 \x01(\x0b\x32&.so101_monitoring.telemetry.PickStatusH\x00\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry.telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRASPCANDIDATE']._serialized_start=58
  _globals['_GRASPCANDIDATE']._serialized_end=289
  _globals['_GRASPCANDIDATE_POSE']._serialized_start=202
  _globals['_GRASPCANDIDATE_POSE']._serialized_end=289
  _globals['_ROBOTCONFIG']._serialized_start=291
  _globals['_ROBOTCONFIG']._serialized_end=376
  _globals['_PICKPLAN']._serialized_start=379
  _globals['_PICKPLAN']._serialized_end=540
  _globals['_PICKSTATUS']._serialized_start=543
  _globals['_PICKSTATUS']._serialized_end=754
  _globals['_PICKSTATUS_STATUS']._serialized_start=703
  _globals['_PICKSTATUS_STATUS']._serialized_end=754
  _globals['_ENVELOPE']._serialized_start=757
  _globals['_ENVELOPE']._serialized_end=968
# @@protoc_insertion_point(module_scope)
